version: "3"

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile-php
    volumes:
      - ./:/var/www/
    networks:
      - symfony

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - symfony_db:/var/lib/mysql:cached
    ports:
      - 3313:3315
    networks:
      - symfony

  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/
    ports:
      - 8001:80
    networks:
      - symfony

volumes:
  symfony_db:

networks:
  symfony:
