when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

    swagger:
        path: /api-doc
        controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        defaults:
            template: swagger-ui.html.twig
