name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mysql
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP-CS-Fixer to fix coding standard issues
        run: |
          curl -L https://cs.symfony.com/download/php-cs-fixer-v3.phar -o php-cs-fixer
          chmod a+x php-cs-fixer
          php php-cs-fixer vendor/bin/php-cs-fixer fix src

      - name: Run PHP Stan static analysis tool
        run: |
          ./vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=1G

      - name: Run Unit Test Cases
        run: |
          php -d memory_limit=256M
          bin/phpunit -c phpunit.unit.xml --testsuite unit